import TopHeader from "@/components/headers/Top.headers";
import MainLayout from "@/layouts/Main.layouts";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Box></Box>
      </MainLayout>
    </>
  );
}
